/**
 * fix_homepage_v4.mjs — Inject CSS via mu-plugin + custom CSS file
 * 
 * WordPress strips <style> tags from post_content.
 * Solution: Upload a CSS file + mu-plugin that enqueues it.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { Client } from 'basic-ftp';

// Parse .env
const envContent = readFileSync('.env', 'utf8');
const env = {};
envContent.split('\n').forEach(line => {
  line = line.trim();
  if (!line || line.startsWith('#')) return;
  const idx = line.indexOf('=');
  if (idx === -1) return;
  const key = line.substring(0, idx).trim();
  let val = line.substring(idx + 1).trim();
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
  env[key] = val;
});

const FTP_HOST = env.FTP_HOST;
const FTP_USER = env.FTP_USER;
const FTP_PASS = env.FTP_PASSWORD || env.FTP_PASS;
const WP_URL = env.WP_URL || env.SITE_URL;
const INJECT_SECRET = env.INJECT_SECRET;

// === 1. Custom CSS file ===
const customCSS = `/* Evergreen Homepage — Custom Elementor Overrides */
/* Generated by fix_homepage_v4.mjs */

/* CTA gradient — matches Stitch .cta-gradient */
.elementor-element-69a22305 {
  background: linear-gradient(135deg, #1D8A43 0%, #28B5E1 100%) !important;
}

/* Hero radial gradient overlay */
.elementor-element-ecf97c6e {
  position: relative;
}
.elementor-element-ecf97c6e::before {
  content: '';
  position: absolute;
  inset: 0;
  background: radial-gradient(circle at 50% 50%, rgba(118,220,138,0.1) 0%, rgba(14,19,32,1) 100%);
  pointer-events: none;
  z-index: 0;
}
.elementor-element-ecf97c6e > .e-con-inner,
.elementor-element-ecf97c6e > .e-child {
  position: relative;
  z-index: 1;
}

/* Stats bar */
.elementor-element-2e6165fc {
  background: #1a1f2d !important;
  border: 1px solid rgba(255,255,255,0.05) !important;
  border-radius: 12px !important;
}

/* CTA button — white */
.elementor-element-d730745d .elementor-button {
  background-color: #FFFFFF !important;
  color: #003916 !important;
  border-radius: 8px !important;
  padding: 16px 40px !important;
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 700 !important;
  font-size: 13px !important;
  letter-spacing: 2px !important;
  text-transform: uppercase !important;
}

/* Hero VER CATÁLOGO button */
.elementor-element-ea522493 .elementor-button {
  background-color: #1D8A43 !important;
  color: #FFFFFF !important;
  border-radius: 8px !important;
  padding: 16px 32px !important;
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 700 !important;
  letter-spacing: 2px !important;
}

/* Hero outline button */
.elementor-element-803be3b3 .elementor-button {
  background-color: transparent !important;
  border: 2px solid #889487 !important;
  color: #FFFFFF !important;
  border-radius: 8px !important;
  padding: 16px 32px !important;
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 700 !important;
  letter-spacing: 2px !important;
}

/* Icon widgets — stacked circle */
.elementor-element-icon_29302187 .elementor-icon,
.elementor-element-icon_44db5797 .elementor-icon,
.elementor-element-icon_7e4cf3f7 .elementor-icon {
  background: rgba(118,220,138,0.1) !important;
  border-radius: 50% !important;
  width: 64px !important;
  height: 64px !important;
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
  color: #76dc8a !important;
  font-size: 30px !important;
}

/* Divider green centered */
.elementor-element-16b62408 .elementor-divider {
  text-align: center;
}
.elementor-element-16b62408 .elementor-divider-separator {
  border-top-color: #76dc8a !important;
  border-top-width: 4px !important;
  width: 80px !important;
  display: inline-block !important;
}

/* Global dark bg for page */
.elementor-page-1758 {
  background: #0E1320 !important;
}

/* Category image cards — ensure images fill */
.elementor-element-7dce1679 img,
.elementor-element-c2f4bf3b img,
.elementor-element-f506a881 img {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  opacity: 0.6;
}

/* Google Fonts for Elementor */
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap');
`;

writeFileSync('temp/evergreen-homepage-custom.css', customCSS);
console.log(`✅ CSS file: ${customCSS.length} bytes`);

// === 2. MU-Plugin to enqueue the CSS ===
const muPlugin = `<?php
/**
 * Plugin Name: Evergreen Homepage Custom CSS
 * Description: Enqueues custom CSS overrides for Elementor homepage
 * Version: 1.0
 */

add_action('wp_enqueue_scripts', function() {
    if (is_front_page() || is_page(1758)) {
        wp_enqueue_style(
            'evergreen-homepage-custom',
            home_url('/wp-content/uploads/evergreen-homepage-custom.css'),
            [],
            '1.0.4'
        );
    }
});
`;

writeFileSync('temp/evergreen-homepage-css.php', muPlugin);
console.log('✅ MU-Plugin generated');

// === 3. Upload both files via FTP ===
const client = new Client();
try {
  await client.access({ host: FTP_HOST, user: FTP_USER, password: FTP_PASS, secure: false });
  console.log('✅ FTP connected');
  
  // Upload CSS to wp-content/uploads/
  await client.uploadFrom('temp/evergreen-homepage-custom.css', '/wp-content/uploads/evergreen-homepage-custom.css');
  console.log('✅ CSS uploaded to /wp-content/uploads/');
  
  // Upload mu-plugin
  try {
    await client.ensureDir('/wp-content/mu-plugins');
    await client.cd('/');
  } catch(e) {
    console.log('mu-plugins dir may already exist');
  }
  await client.uploadFrom('temp/evergreen-homepage-css.php', '/wp-content/mu-plugins/evergreen-homepage-css.php');
  console.log('✅ MU-Plugin uploaded to /wp-content/mu-plugins/');
  
  client.close();
  
  // === 4. Purge cache ===
  const purgePhp = `<?php
if (!isset($_GET['token']) || $_GET['token'] !== '${INJECT_SECRET}') {
    http_response_code(403); die('forbidden');
}
require_once(__DIR__ . '/wp-load.php');
// Clear page cache
clean_post_cache(1758);
delete_post_meta(1758, '_elementor_css');
delete_option('_elementor_global_css');
if (function_exists('wp_cache_flush')) wp_cache_flush();
// Try LiteSpeed purge
if (class_exists('LiteSpeed_Cache_API')) {
    LiteSpeed_Cache_API::purge_all();
}
@unlink(__FILE__);
echo json_encode(['status' => 'cache_purged']);
`;
  
  writeFileSync('temp/purge_cache.php', purgePhp);
  const client2 = new Client();
  await client2.access({ host: FTP_HOST, user: FTP_USER, password: FTP_PASS, secure: false });
  await client2.uploadFrom('temp/purge_cache.php', '/purge_cache.php');
  client2.close();
  
  const resp = await fetch(`${WP_URL}/purge_cache.php?token=${INJECT_SECRET}`);
  console.log(`📦 Cache purge: ${await resp.text()}`);
  
} catch (err) {
  console.error('❌', err.message);
}

console.log('\n🔗 Verify CSS is loading:');
console.log(`   ${WP_URL}/wp-content/uploads/evergreen-homepage-custom.css`);
