/**
 * fix_images_final.mjs — Fix category images rendering + hero improvements
 * 
 * ROOT CAUSE: CSS in custom file sets img to position:absolute + inset:0
 * but the widget container (.elementor-widget-image) has height:0px.
 * The images ARE there but invisible because they overflow a 0-height container.
 * 
 * FIX: Update CSS to remove absolute positioning, use proper height + object-fit.
 * Also update _elementor_data to remove bad positioning settings.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { Client } from 'basic-ftp';

// Parse .env
const envContent = readFileSync('.env', 'utf8');
const env = {};
envContent.split('\n').forEach(line => {
  line = line.trim();
  if (!line || line.startsWith('#')) return;
  const idx = line.indexOf('=');
  if (idx === -1) return;
  const key = line.substring(0, idx).trim();
  let val = line.substring(idx + 1).trim();
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
  env[key] = val;
});

const FTP_HOST = env.FTP_HOST;
const FTP_USER = env.FTP_USER;
const FTP_PASS = env.FTP_PASSWORD || env.FTP_PASS;
const WP_URL = env.WP_URL || env.SITE_URL;
const INJECT_SECRET = env.INJECT_SECRET;
const HOMEPAGE_ID = 1758;

// ============================================================
// 1. Updated CSS — Fix image cards + improve hero
// ============================================================
const customCSS = `/* Evergreen Homepage — Custom Elementor Overrides */
/* Generated by fix_images_final.mjs — v2.0 */
/* Last update: ${new Date().toISOString()} */

/* ========================================
   GLOBAL
   ======================================== */

/* Global dark bg for page */
.elementor-page-1758 {
  background: #0E1320 !important;
}

/* Google Fonts */
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap');

/* ========================================
   HERO SECTION
   ======================================== */

/* Hero radial gradient overlay */
.elementor-element-ecf97c6e {
  position: relative;
}
.elementor-element-ecf97c6e::before {
  content: '';
  position: absolute;
  inset: 0;
  background: radial-gradient(circle at 50% 50%, rgba(118,220,138,0.1) 0%, rgba(14,19,32,1) 100%);
  pointer-events: none;
  z-index: 0;
}
.elementor-element-ecf97c6e > .e-con-inner,
.elementor-element-ecf97c6e > .e-child,
.elementor-element-ecf97c6e > .elementor-element {
  position: relative;
  z-index: 1;
}

/* Hero VER CATÁLOGO button */
.elementor-element-ea522493 .elementor-button {
  background-color: #1D8A43 !important;
  color: #FFFFFF !important;
  border-radius: 8px !important;
  padding: 16px 32px !important;
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 700 !important;
  letter-spacing: 2px !important;
}

/* Hero outline button */
.elementor-element-803be3b3 .elementor-button {
  background-color: transparent !important;
  border: 2px solid #889487 !important;
  color: #FFFFFF !important;
  border-radius: 8px !important;
  padding: 16px 32px !important;
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 700 !important;
  letter-spacing: 2px !important;
}

/* ========================================
   STATS BAR
   ======================================== */

.elementor-element-2e6165fc {
  background: #1a1f2d !important;
  border: 1px solid rgba(255,255,255,0.05) !important;
  border-radius: 12px !important;
}

/* ========================================
   CATEGORY IMAGE CARDS — THE CRITICAL FIX
   ======================================== */

/* Card containers — overflow hidden + relative for clipping */
.elementor-element-7dce1679,
.elementor-element-c2f4bf3b,
.elementor-element-f506a881 {
  position: relative !important;
  overflow: hidden !important;
  border-radius: 12px !important;
  min-height: 280px !important;
}

/* Image widgets inside cards — fill the entire card */
.elementor-element-7dce1679 .elementor-widget-image,
.elementor-element-c2f4bf3b .elementor-widget-image,
.elementor-element-f506a881 .elementor-widget-image {
  position: absolute !important;
  inset: 0 !important;
  width: 100% !important;
  height: 100% !important;
  z-index: 0 !important;
}

.elementor-element-7dce1679 .elementor-widget-image .elementor-widget-container,
.elementor-element-c2f4bf3b .elementor-widget-image .elementor-widget-container,
.elementor-element-f506a881 .elementor-widget-image .elementor-widget-container {
  width: 100% !important;
  height: 100% !important;
}

/* Images — fill and cover */
.elementor-element-7dce1679 .elementor-widget-image img,
.elementor-element-c2f4bf3b .elementor-widget-image img,
.elementor-element-f506a881 .elementor-widget-image img {
  width: 100% !important;
  height: 100% !important;
  object-fit: cover !important;
  opacity: 0.5 !important;
  position: static !important;
  display: block !important;
}

/* Dark gradient overlay on image cards for text readability */
.elementor-element-7dce1679::after,
.elementor-element-c2f4bf3b::after,
.elementor-element-f506a881::after {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(to top, rgba(14,19,32,0.9) 0%, rgba(14,19,32,0.3) 50%, rgba(14,19,32,0.1) 100%);
  pointer-events: none;
  z-index: 1;
}

/* Text elements inside cards — above overlay */
.elementor-element-7dce1679 .elementor-widget-heading,
.elementor-element-7dce1679 .elementor-widget-text-editor,
.elementor-element-c2f4bf3b .elementor-widget-heading,
.elementor-element-c2f4bf3b .elementor-widget-text-editor,
.elementor-element-f506a881 .elementor-widget-heading,
.elementor-element-f506a881 .elementor-widget-text-editor {
  position: relative;
  z-index: 2;
}

/* ========================================
   CTA SECTION
   ======================================== */

/* CTA gradient — matches Stitch .cta-gradient */
.elementor-element-69a22305 {
  background: linear-gradient(135deg, #1D8A43 0%, #28B5E1 100%) !important;
}

/* CTA button — white */
.elementor-element-d730745d .elementor-button {
  background-color: #FFFFFF !important;
  color: #003916 !important;
  border-radius: 8px !important;
  padding: 16px 40px !important;
  font-family: 'Space Grotesk', sans-serif !important;
  font-weight: 700 !important;
  font-size: 13px !important;
  letter-spacing: 2px !important;
  text-transform: uppercase !important;
}

/* ========================================
   VALUE PROPS
   ======================================== */

/* Divider green centered */
.elementor-element-16b62408 .elementor-divider {
  text-align: center;
}
.elementor-element-16b62408 .elementor-divider-separator {
  border-top-color: #76dc8a !important;
  border-top-width: 4px !important;
  width: 80px !important;
  display: inline-block !important;
}

/* Icon widgets — stacked circle */
.elementor-element-icon_29302187 .elementor-icon,
.elementor-element-icon_44db5797 .elementor-icon,
.elementor-element-icon_7e4cf3f7 .elementor-icon {
  background: rgba(118,220,138,0.1) !important;
  border-radius: 50% !important;
  width: 64px !important;
  height: 64px !important;
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
  color: #76dc8a !important;
  font-size: 30px !important;
}
`;

writeFileSync('temp/evergreen-homepage-custom.css', customCSS);
console.log(`✅ CSS file: ${customCSS.length} bytes`);

// ============================================================
// 2. MU-Plugin (update version to bust cache)
// ============================================================
const muPlugin = `<?php
/**
 * Plugin Name: Evergreen Homepage Custom CSS
 * Description: Enqueues custom CSS overrides for Elementor homepage
 * Version: 2.0
 */

add_action('wp_enqueue_scripts', function() {
    if (is_front_page() || is_page(1758)) {
        wp_enqueue_style(
            'evergreen-homepage-custom',
            home_url('/wp-content/uploads/evergreen-homepage-custom.css'),
            [],
            '2.0.0'
        );
    }
});
`;

writeFileSync('temp/evergreen-homepage-css.php', muPlugin);

// ============================================================
// 3. PHP to fix _elementor_data — remove absolute positioning from images
// ============================================================
const phpFixData = `<?php
if (!isset($_GET['token']) || $_GET['token'] !== '${INJECT_SECRET}') {
    http_response_code(403); die('forbidden');
}
header('Content-Type: application/json');
require_once(__DIR__ . '/wp-load.php');

$page_id = ${HOMEPAGE_ID};
$json_raw = get_post_meta($page_id, '_elementor_data', true);

// Handle double-encoding
if (is_string($json_raw)) {
    $data = json_decode($json_raw, true);
    if ($data === null) {
        $json_raw = stripslashes($json_raw);
        $data = json_decode($json_raw, true);
    }
}

if (!$data) {
    echo json_encode(['error' => 'Failed to parse _elementor_data']);
    @unlink(__FILE__);
    exit;
}

// Fix image widgets — remove absolute positioning settings
$image_widget_ids = ['02453e5a', '3ca2b9d3', 'd5c192f5'];
$fixes = [];

function fix_image_widgets(&$elements, $ids, &$fixes) {
    foreach ($elements as &$el) {
        $id = isset($el['id']) ? $el['id'] : '';
        
        if (isset($el['widgetType']) && $el['widgetType'] === 'image' && in_array($id, $ids)) {
            // Remove absolute positioning
            unset($el['settings']['_position']);
            unset($el['settings']['_offset_x']);
            unset($el['settings']['_offset_y']);
            unset($el['settings']['_element_width']);
            
            // Set proper display settings
            $el['settings']['image_size'] = 'full';
            $el['settings']['width'] = ['size' => 100, 'unit' => '%'];
            
            // Remove forced height — CSS will handle it
            unset($el['settings']['height']);
            unset($el['settings']['object-fit']);
            
            $fixes[] = $id;
        }
        
        if (!empty($el['elements'])) {
            fix_image_widgets($el['elements'], $ids, $fixes);
        }
    }
}

fix_image_widgets($data, $image_widget_ids, $fixes);

// Also fix parent containers — ensure they have proper settings
$card_ids = ['7dce1679', 'c2f4bf3b', 'f506a881'];

function fix_card_containers(&$elements, $ids) {
    foreach ($elements as &$el) {
        $id = isset($el['id']) ? $el['id'] : '';
        
        if (in_array($id, $ids)) {
            $el['settings']['min_height'] = ['size' => 280, 'unit' => 'px'];
            $el['settings']['flex_direction'] = 'column';
            $el['settings']['flex_justify_content'] = 'flex-end';
            $el['settings']['position'] = 'relative';
            $el['settings']['overflow'] = 'hidden';
        }
        
        if (!empty($el['elements'])) {
            fix_card_containers($el['elements'], $ids);
        }
    }
}

fix_card_containers($data, $card_ids);

// Save updated _elementor_data
$new_json = wp_json_encode($data);
update_post_meta($page_id, '_elementor_data', wp_slash($new_json));

// Rebuild post_content
function rebuild_html($elements, $depth = 0) {
    $html = '';
    foreach ($elements as $el) {
        $type = isset($el['elType']) ? $el['elType'] : '';
        $id = isset($el['id']) ? $el['id'] : '';
        $settings = isset($el['settings']) ? $el['settings'] : [];
        
        if ($type === 'container') {
            $is_inner = !empty($el['isInner']) || $depth > 0;
            $parent_class = $is_inner ? 'e-child' : 'e-parent';
            $boxed = (isset($settings['content_width']) && $settings['content_width'] === 'boxed') ? 'e-con-boxed' : 'e-con-full';
            
            $html .= '<div class="elementor-element elementor-element-' . $id . ' ' . $boxed . ' e-flex e-con ' . $parent_class . '" data-id="' . $id . '" data-element_type="container">';
            if ($boxed === 'e-con-boxed') {
                $html .= '<div class="e-con-inner">';
            }
            if (!empty($el['elements'])) {
                $html .= rebuild_html($el['elements'], $depth + 1);
            }
            if ($boxed === 'e-con-boxed') {
                $html .= '</div>';
            }
            $html .= '</div>';
        } elseif ($type === 'widget') {
            $wtype = isset($el['widgetType']) ? $el['widgetType'] : '';
            $html .= '<div class="elementor-element elementor-element-' . $id . ' elementor-widget elementor-widget-' . $wtype . '" data-id="' . $id . '" data-element_type="widget" data-widget_type="' . $wtype . '.default">';
            $html .= '<div class="elementor-widget-container">';
            
            switch ($wtype) {
                case 'heading':
                    $tag = isset($settings['header_size']) ? $settings['header_size'] : 'h2';
                    $title = isset($settings['title']) ? $settings['title'] : '';
                    $html .= '<' . $tag . ' class="elementor-heading-title elementor-size-default">' . $title . '</' . $tag . '>';
                    break;
                case 'text-editor':
                    $editor = isset($settings['editor']) ? $settings['editor'] : '';
                    $html .= $editor;
                    break;
                case 'button':
                    $text = isset($settings['text']) ? $settings['text'] : '';
                    $url = isset($settings['link']['url']) ? $settings['link']['url'] : '#';
                    $html .= '<a class="elementor-button elementor-button-link elementor-size-sm" href="' . esc_attr($url) . '"><span class="elementor-button-content-wrapper"><span class="elementor-button-text">' . esc_html($text) . '</span></span></a>';
                    break;
                case 'image':
                    $img_url = isset($settings['image']['url']) ? $settings['image']['url'] : '';
                    $img_alt = isset($settings['image']['alt']) ? $settings['image']['alt'] : '';
                    if ($img_url) {
                        $html .= '<img decoding="async" src="' . esc_attr($img_url) . '" alt="' . esc_attr($img_alt) . '" loading="lazy" />';
                    }
                    break;
                case 'divider':
                    $html .= '<div class="elementor-divider"><span class="elementor-divider-separator"></span></div>';
                    break;
                case 'icon':
                    $icon = isset($settings['selected_icon']['value']) ? $settings['selected_icon']['value'] : '';
                    $html .= '<div class="elementor-icon-wrapper"><div class="elementor-icon"><i class="' . $icon . '"></i></div></div>';
                    break;
                case 'icon-box':
                    $icon = isset($settings['selected_icon']['value']) ? $settings['selected_icon']['value'] : '';
                    $title = isset($settings['title_text']) ? $settings['title_text'] : '';
                    $desc = isset($settings['description_text']) ? $settings['description_text'] : '';
                    $tag = isset($settings['title_size']) ? $settings['title_size'] : 'h3';
                    $html .= '<div class="elementor-icon-box-wrapper"><div class="elementor-icon-box-icon"><span class="elementor-icon"><i class="' . $icon . '"></i></span></div><div class="elementor-icon-box-content"><' . $tag . ' class="elementor-icon-box-title">' . $title . '</' . $tag . '><p class="elementor-icon-box-description">' . $desc . '</p></div></div>';
                    break;
                case 'counter':
                    $end = isset($settings['ending_number']) ? $settings['ending_number'] : '0';
                    $prefix = isset($settings['prefix']) ? $settings['prefix'] : '';
                    $suffix = isset($settings['suffix']) ? $settings['suffix'] : '';
                    $title = isset($settings['title']) ? $settings['title'] : '';
                    $html .= '<div class="elementor-counter"><div class="elementor-counter-number-wrapper"><span class="elementor-counter-number-prefix">' . $prefix . '</span><span class="elementor-counter-number" data-to-value="' . $end . '">' . $end . '</span><span class="elementor-counter-number-suffix">' . $suffix . '</span></div><div class="elementor-counter-title">' . $title . '</div></div>';
                    break;
            }
            
            $html .= '</div></div>';
        }
    }
    return $html;
}

$rebuilt = '<div data-elementor-type="wp-page" data-elementor-id="' . $page_id . '" class="elementor elementor-' . $page_id . '">';
$rebuilt .= rebuild_html($data);
$rebuilt .= '</div>';

// Use $wpdb to avoid wp_kses sanitization
global $wpdb;
$wpdb->update(
    $wpdb->posts,
    ['post_content' => $rebuilt],
    ['ID' => $page_id],
    ['%s'],
    ['%d']
);

// Clear ALL caches
delete_post_meta($page_id, '_elementor_css');
delete_post_meta($page_id, '_elementor_inline_svg');
delete_post_meta($page_id, '_elementor_page_assets');
update_post_meta($page_id, '_elementor_version', '0.0.0');
clean_post_cache($page_id);
delete_option('_elementor_global_css');
if (function_exists('wp_cache_flush')) wp_cache_flush();
if (class_exists('LiteSpeed_Cache_API')) {
    LiteSpeed_Cache_API::purge_all();
}

@unlink(__FILE__);

echo json_encode([
    'status' => 'success',
    'image_widgets_fixed' => $fixes,
    'html_length' => strlen($rebuilt),
    'images_in_html' => substr_count($rebuilt, '<img'),
    'cache' => 'flushed'
]);
`;

writeFileSync('temp/fix_images_final.php', phpFixData);
console.log(`✅ PHP fix script: ${phpFixData.length} bytes`);

// ============================================================
// 4. Upload all files via FTP
// ============================================================
const client = new Client();
try {
  await client.access({ host: FTP_HOST, user: FTP_USER, password: FTP_PASS, secure: false });
  console.log('✅ FTP connected');
  
  // Upload CSS (updated)
  await client.uploadFrom('temp/evergreen-homepage-custom.css', '/wp-content/uploads/evergreen-homepage-custom.css');
  console.log('✅ CSS uploaded');
  
  // Upload mu-plugin (updated version)
  await client.uploadFrom('temp/evergreen-homepage-css.php', '/wp-content/mu-plugins/evergreen-homepage-css.php');
  console.log('✅ MU-Plugin uploaded');
  
  // Upload PHP fix script
  await client.uploadFrom('temp/fix_images_final.php', '/fix_images_final.php');
  console.log('✅ Fix PHP uploaded');
  
  client.close();
  
  // Execute PHP to fix _elementor_data + rebuild post_content
  const url = `${WP_URL}/fix_images_final.php?token=${INJECT_SECRET}`;
  console.log('⏳ Executing fix...');
  const resp = await fetch(url, { headers: { 'User-Agent': 'EvergreenBot/1.0' } });
  const text = await resp.text();
  console.log(`📦 Response (${resp.status}): ${text}`);
  
  try {
    const result = JSON.parse(text);
    console.log('\n✅ Fix result:', JSON.stringify(result, null, 2));
  } catch {
    console.log('⚠️ Non-JSON response');
  }
  
} catch (err) {
  console.error('❌ Error:', err.message);
}

console.log('\n🔗 Verify: ' + WP_URL);
